<?php

require_once('fpdf181/fpdf.php');
require_once('FPDI-1.6.1/fpdi.php');

class PdfMerger
{
    /**
     * Merges all 
     * @param type $path
     */
    public static function mergeDir($sourcepath)
    {
        $files2 = scandir($sourcepath);
        $files = [];
        foreach($files2 as $file){
            if ( strtoupper(pathinfo($file)['extension']) == "PDF"){
                $files[] = $sourcepath . "/" . $file;
            }
        }

        $pageCount = 0;
        // initiate FPDI
        $pdf = new FPDI();

        // iterate through the files
        foreach ($files AS $file) {
            // get the page count
            $pageCount = $pdf->setSourceFile($file);
            // iterate through all pages
            for ($pageNo = 1; $pageNo <= $pageCount; $pageNo++) {
                // import a page
                $templateId = $pdf->importPage($pageNo);
                // get the size of the imported page
                $size = $pdf->getTemplateSize($templateId);

                // create a page (landscape or portrait depending on the imported page size)
                if ($size['w'] > $size['h']) {
                    $pdf->AddPage('L', array($size['w'], $size['h']));
                } else {
                    $pdf->AddPage('P', array($size['w'], $size['h']));
                }

                // use the imported page
                $pdf->useTemplate($templateId);

                //$pdf->SetFont('Helvetica');
                //$pdf->SetXY(5, 5);
                //$pdf->Write(8, 'Generated by FPDI');
            }
        }
        $pdf->Output();
    }

    public static function getUploadForm()
    {
        $google =<<<G
<script type="text/javascript"><!--
    google_ad_client = "ca-pub-7137239348401468";
    /* guyBredeBalk */
    google_ad_slot = "7151863716";
    google_ad_width = 728;
    google_ad_height = 90;
    //-->
    </script>
    <script type="text/javascript"
    src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
G;
        
        return <<<FRM
<!DOCTYPE html>
<html>
    <head>
        <title>PDF merger</title>
        <META NAME="DESCRIPTION" CONTENT="Merge a number of pdf files into one pdf file with Tolima's online pdfmerger." />
        <META NAME="KEYWORDS" CONTENT="pdf merger, merge pdf files,merging pdf files" />
        <META charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>
    <body>
        <div class='container'>
            <div class='row'>
                <div class='col-md-10 col-md-offset-1'>
                    {$google}
                    <h1>Online PDF merger</h1>
                    <p>
                    <h4>Merge a number of pdf files into one pdf file.<h4><br/>
                    Do you have whole stack of small pdf documents?  Or you sent a list of invoices 
                    to your accountant which he then has to print one by one.<br/>
                    You can spare yourself or your accountant a lot of this tedious work by merging all the pdf'files together with this online pdf merger. 
                    </p>
                    <br/>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h2>Select pdf files to merge:</h2>
                        </div>
                        <div class="panel-body">
                            
                            <form method='post' enctype="multipart/form-data">
                                <input type='hidden' name='upl' value='1' />
                                
                                <input type="file" name="upload[]" multiple="" id="fileToUpload" class='btn btn-info ' ><br/>
                                <input type='submit' class='btn btn-primary' value='merge' /><BR/><br/>
                                {$google}
                            </form>
                        </div>
                    </div><br/>
                    <a class="twitter-share-button"
                        href="https://twitter.com/intent/tweet?text=Merge a number of pdf files into one pdf file with Tolima's online pdf merger - ">
                      Tweet</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                </div>
            </div>
        </div>
    </body>
</html>
FRM;
    }

    public static function processUploadForm()
    {
        if (! isset($_POST['upl'])){
            return false;
        }

        //upload files
        $target_map = "dir" . time();
        mkdir($target_map);
        $target_dir = $target_map . "/";
        $total = count($_FILES['upload']['name']);
        for($i=0; $i<$total; $i++) {
            $tmpFilePath = $_FILES['upload']['tmp_name'][$i];
            if ($tmpFilePath != ""){
                $newFilePath = $target_dir . $_FILES['upload']['name'][$i];
                if (move_uploaded_file($tmpFilePath, $newFilePath)) {
                }
            }
        }
        //do the merge
        PdfMerger::mergeDir($target_map);
        return true;
    }
}

if (!PdfMerger::processUploadForm()){
    echo PdfMerger::getUploadForm();
}
