<?php

require_once('fpdf181/fpdf.php');
require_once('FPDI-1.6.1/fpdi.php');

class PdfMerger
{
    /**
     * Merges all 
     * @param type $path
     */
    public static function mergeDir($sourcepath)
    {
        $files2 = scandir($sourcepath);
        $files = [];
        foreach($files2 as $file){
            if ( strtoupper(pathinfo($file)['extension']) == "PDF"){
                $files[] = $sourcepath . "/" . $file;
            }
        }
        $pageCount = 0;
        // initiate FPDI
        $pdf = new FPDI();

        // iterate through the files
        foreach ($files AS $file) {
            // get the page count
            $pageCount = $pdf->setSourceFile($file);
            // iterate through all pages
            for ($pageNo = 1; $pageNo <= $pageCount; $pageNo++) {
                // import a page
                $templateId = $pdf->importPage($pageNo);
                // get the size of the imported page
                $size = $pdf->getTemplateSize($templateId);

                // create a page (landscape or portrait depending on the imported page size)
                if ($size['w'] > $size['h']) {
                    $pdf->AddPage('L', array($size['w'], $size['h']));
                } else {
                    $pdf->AddPage('P', array($size['w'], $size['h']));
                }

                // use the imported page
                $pdf->useTemplate($templateId);

                //$pdf->SetFont('Helvetica');
                //$pdf->SetXY(5, 5);
                //$pdf->Write(8, 'Generated by FPDI');
            }
        }
        $pdf->Output();
    }

    public static function getUploadForm()
    {
        return <<<FRM
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <form method='post'>
            <input type='hidden' name='upl' value='1' />
            <input type='submit' />
        </form>
    </body>
</html>
FRM;
    }

    public static function processUploadForm()
    {
        if (! isset($_POST['upl'])){
            return false;
        }
        PdfMerger::mergeDir("theplace");
        return true;
    }
}

if (!PdfMerger::processUploadForm()){
    echo PdfMerger::getUploadForm();
}
