<?php

require_once('fpdf181/fpdf.php');
require_once('FPDI-1.6.1/fpdi.php');

$files2 = scandir("pdfs");
$files = [];
foreach($files2 as $file){
    if ( strtoupper(pathinfo($file)['extension']) == "PDF"){
        $files[] = "pdfs/" . $file;
    }
}
$pageCount = 0;
// initiate FPDI
$pdf = new FPDI();

// iterate through the files
foreach ($files AS $file) {
    // get the page count
    $pageCount = $pdf->setSourceFile($file);
    // iterate through all pages
    for ($pageNo = 1; $pageNo <= 1; $pageNo++) {
        // import a page
        $templateId = $pdf->importPage($pageNo);
        // get the size of the imported page
        $size = $pdf->getTemplateSize($templateId);

        // create a page (landscape or portrait depending on the imported page size)
        if ($size['w'] > $size['h']) {
            $pdf->AddPage('L', array($size['w'], $size['h']));
        } else {
            $pdf->AddPage('P', array($size['w'], $size['h']));
        }

        // use the imported page
        $pdf->useTemplate($templateId);

        //$pdf->SetFont('Helvetica');
        //$pdf->SetXY(5, 5);
        //$pdf->Write(8, 'Generated by FPDI');
    }
}
$pdf->Output();
/*
$pdf = new FPDI();

$pageCount = $pdf->setSourceFile('ALT00429010.pdf');
$pdf->addPage();
$tplIdx = $pdf->importPage(1, '/MediaBox');
$pdf->useTemplate($tplIdx, 10, 10, 90);
$pdf->Output();
 */